TRUNCATE TABLE ORDERLIJN;
TRUNCATE TABLE KLANTORDER;
TRUNCATE TABLE KLANT;
TRUNCATE TABLE WERKNEMER;
TRUNCATE TABLE LEVERING;
TRUNCATE TABLE WINKEL;
TRUNCATE TABLE BEDRIJF;
TRUNCATE TABLE CONSOLE;


--console
INSERT INTO CONSOLE (CONSOLENAAM, PRIJS, RELEASE)
VALUES ('Xbox series x', 559, to_date('10-11-2020', 'DD/MM/YYYY'));
INSERT INTO CONSOLE (CONSOLENAAM, PRIJS, RELEASE)
VALUES ('Nintendo Switch', 210, to_date('16-3-2017', 'DD/MM/YYYY'));
INSERT INTO CONSOLE (CONSOLENAAM, PRIJS, RELEASE)
VALUES ('Steam Deck', 779, to_date('20-2-2022', 'DD/MM/YYYY'));
INSERT INTO CONSOLE (CONSOLENAAM, PRIJS, RELEASE)
VALUES ('Playstation 4', 420, to_date('14-10-2017', 'DD/MM/YYYY'));
INSERT INTO CONSOLE (CONSOLENAAM, PRIJS, RELEASE)
VALUES ('Playstation 5', 599, to_date('20-11-2020', 'DD/MM/YYYY'));

--bedrijf
INSERT INTO BEDRIJF (NAAM, BEDRIJF_ADRES, BEDRIJF_LAND, CONSOLE_CONSOLEID)
VALUES ('Sony Belgium', 'Leonardo da Vincilaan 7 1920', 'België',
        (select CONSOLEID from CONSOLE where CONSOLENAAM = 'Playstation 4'));
INSERT INTO BEDRIJF (NAAM, BEDRIJF_ADRES, BEDRIJF_LAND, CONSOLE_CONSOLEID)
VALUES ('Sony', 'Konan Minato-ku 171 108', 'Japan',
        (select CONSOLEID from CONSOLE where CONSOLENAAM = 'Playstation 5'));
INSERT INTO BEDRIJF (NAAM, BEDRIJF_ADRES, BEDRIJF_LAND, CONSOLE_CONSOLEID)
VALUES ('Microsoft', 'Evert van de Beekstraat 354 1118', 'Nederland',
        (select CONSOLEID from CONSOLE where CONSOLENAAM = 'Xbox series x'));
INSERT INTO BEDRIJF (NAAM, BEDRIJF_ADRES, BEDRIJF_LAND, CONSOLE_CONSOLEID)
VALUES ('Valve', 'NE St 4th 10400', 'Amerika',
        (select CONSOLEID from CONSOLE where CONSOLENAAM = 'Steam Deck'));
INSERT INTO BEDRIJF (NAAM, BEDRIJF_ADRES, BEDRIJF_LAND, CONSOLE_CONSOLEID)
VALUES ('Nintendo', 'Ave. NE Redmond 150th 4600', 'Amerika',
        (select CONSOLEID from CONSOLE where CONSOLENAAM = 'Nintendo Switch'));


--winkel
INSERT INTO WINKEL (WINKEL_NAAM, WINKEL_EMAIL, STOCK, WINKEL_ADRES, WINKEL_TELEFOON)
VALUES ('MediaMarkt', 'mediamarkt@gmail.com', 50, 'Keyserlei 7 2000', '032241040');
INSERT INTO WINKEL (WINKEL_NAAM, WINKEL_EMAIL, STOCK, WINKEL_ADRES, WINKEL_TELEFOON)
VALUES ('Gamemania', 'gamemania@gmail.com', 41, 'Frankrijklei 28 2000', '032273838');
INSERT INTO WINKEL (WINKEL_NAAM, WINKEL_EMAIL, STOCK, WINKEL_ADRES, WINKEL_TELEFOON)
VALUES ('The Body Shop', 'thebodyshop@gmail.com', 30, 'Huidevetterstraat 2 2000', '032333444');
INSERT INTO WINKEL (WINKEL_NAAM, WINKEL_EMAIL, STOCK, WINKEL_ADRES, WINKEL_TELEFOON)
VALUES ('JBC', 'jbcstore@gmail.com', 10, 'Italielei 44 2000', '032555666');
INSERT INTO WINKEL (WINKEL_NAAM, WINKEL_EMAIL, STOCK, WINKEL_ADRES, WINKEL_TELEFOON)
VALUES ('H&M', 'hmstore@gmail.com', 3, 'Meir 100 2000', '032222111');

--levering
--where veranderen naar winkel_name
INSERT INTO LEVERING (LEVERING_ADRES, TOTALE_PRIJS, LEVERINGSDATUM, CONSOLE_CONSOLEID, WINKEL_WINKEL_ID)
VALUES (('Keyserlei 7, 2000'), 559, to_date('9-03-2023', 'DD/MM/YYYY'),
        (select CONSOLEID from CONSOLE where CONSOLENAAM = 'Xbox series x'),
        (select WINKEL_ID from WINKEL where WINKEL_ADRES = 'Keyserlei 7 2000'));
INSERT INTO LEVERING (LEVERING_ADRES, TOTALE_PRIJS, LEVERINGSDATUM, CONSOLE_CONSOLEID, WINKEL_WINKEL_ID)
VALUES ('Meir 100, 2000', 630, to_date('1-04-2023', 'DD/MM/YYYY'),
        (select CONSOLEID from CONSOLE where CONSOLENAAM = 'Nintendo Switch'),
        (select WINKEL_ID from WINKEL where WINKEL_ADRES = 'Meir 100 2000'));
INSERT INTO LEVERING (LEVERING_ADRES, TOTALE_PRIJS, LEVERINGSDATUM, CONSOLE_CONSOLEID, WINKEL_WINKEL_ID)
VALUES ('Meir 100, 2000', 411, to_date('1-04-2023', 'DD/MM/YYYY'),
        (select CONSOLEID from CONSOLE where CONSOLENAAM = 'Playstation 4'),
        (select WINKEL_ID from WINKEL where WINKEL_ADRES = 'Meir 100 2000'));
INSERT INTO LEVERING (LEVERING_ADRES, TOTALE_PRIJS, LEVERINGSDATUM, CONSOLE_CONSOLEID, WINKEL_WINKEL_ID)
VALUES ('Frankrijklei 28, 2000', 728, to_date('1-03-2023', 'DD/MM/YYYY'),
        (select CONSOLEID from CONSOLE where CONSOLENAAM = 'Playstation 5'),
        (select WINKEL_ID from WINKEL where WINKEL_ADRES = 'Frankrijklei 28 2000'));
INSERT INTO LEVERING (LEVERING_ADRES, TOTALE_PRIJS, LEVERINGSDATUM, CONSOLE_CONSOLEID, WINKEL_WINKEL_ID)
VALUES ('Italielei 44, 2000', 1558, to_date('8-03-2023', 'DD/MM/YYYY'),
        (select CONSOLEID from CONSOLE where CONSOLENAAM = 'Steam Deck'),
        (select WINKEL_ID from WINKEL where WINKEL_ADRES = 'Italielei 44 2000'));

--werknemer
INSERT INTO WERKNEMER (WERKNEMER_VOORNAAM, WERKNEMER_ACHTERNAAM, IS_MANAGER, WINKEL_WINKEL_ID)
VALUES ('John', 'White', 'false', (select WINKEL_ID from WINKEL where WINKEL_NAAM = 'MediaMarkt'));
INSERT INTO WERKNEMER (WERKNEMER_VOORNAAM, WERKNEMER_ACHTERNAAM, IS_MANAGER, WINKEL_WINKEL_ID)
VALUES ('Walter', 'White', 'true', (select WINKEL_ID from WINKEL where WINKEL_NAAM = 'MediaMarkt'));
INSERT INTO WERKNEMER (WERKNEMER_VOORNAAM, WERKNEMER_ACHTERNAAM, IS_MANAGER, WINKEL_WINKEL_ID)
VALUES ('Filip', 'Smith', 'false', (select WINKEL_ID from WINKEL where WINKEL_NAAM = 'Gamemania'));
INSERT INTO WERKNEMER (WERKNEMER_VOORNAAM, WERKNEMER_ACHTERNAAM, IS_MANAGER, WINKEL_WINKEL_ID)
VALUES ('Ella', 'Bord', 'false', (select WINKEL_ID from WINKEL where WINKEL_NAAM = 'JBC'));
INSERT INTO WERKNEMER (WERKNEMER_VOORNAAM, WERKNEMER_ACHTERNAAM, IS_MANAGER, WINKEL_WINKEL_ID)
VALUES ('Hafsa', 'Chanoef', 'false', (select WINKEL_ID from WINKEL where WINKEL_NAAM = 'JBC'));

--klant
INSERT INTO KLANT (NAAM, LEEFTIJD, KLANT_ADRES)
VALUES ('Sophie Vandenberghe', 27, 'Korte Altaarstraat 8 2100');
INSERT INTO KLANT (NAAM, LEEFTIJD, KLANT_ADRES)
VALUES ('Tom Verstraeten', 43, 'Pelikaanstraat 78 1900');
INSERT INTO KLANT (NAAM, LEEFTIJD, KLANT_ADRES)
VALUES ('Lise De Vries', 32, 'Oude Leeuwenrui 8 2020');
INSERT INTO KLANT (NAAM, LEEFTIJD, KLANT_ADRES)
VALUES ('Karen Willems', 29, 'Brouwersvliet 23 2100');
INSERT INTO KLANT (NAAM, LEEFTIJD, KLANT_ADRES)
VALUES ('Bob Debower', 17, 'Korte Altaarstraat 8 2060');

--klantorder
INSERT INTO KLANTORDER (KLANT_KLANTID, WINKEL_WINKEL_ID, PRIJS, ORDER_DATUM)
VALUES ((select KLANTID from KLANT where NAAM = 'Sophie Vandenberghe'),
        (select WINKEL_ID from WINKEL where WINKEL_ADRES = 'Frankrijklei 28 2000'), 840,
        to_date('11-12-2020', 'DD/MM/YYYY'));
INSERT INTO KLANTORDER (KLANT_KLANTID, WINKEL_WINKEL_ID, PRIJS, ORDER_DATUM)
VALUES ((select KLANTID from KLANT where NAAM = 'Sophie Vandenberghe'),
        (select WINKEL_ID from WINKEL where WINKEL_ADRES = 'Frankrijklei 28 2000'), 420,
        to_date('20-6-2020', 'DD/MM/YYYY'));
INSERT INTO KLANTORDER (KLANT_KLANTID, WINKEL_WINKEL_ID, PRIJS, ORDER_DATUM)
VALUES ((select KLANTID from KLANT where NAAM = 'Karen Willems'),
        (select WINKEL_ID from WINKEL where WINKEL_ADRES = 'Huidevetterstraat 2 2000'), 210,
        to_date('2-4-2021', 'DD/MM/YYYY'));
INSERT INTO KLANTORDER (KLANT_KLANTID, WINKEL_WINKEL_ID, PRIJS, ORDER_DATUM)
VALUES ((select KLANTID from KLANT where NAAM = 'Bob Debower'),
        (select WINKEL_ID from WINKEL where WINKEL_ADRES = 'Keyserlei 7 2000'), 779,
        to_date('17-4-2023', 'DD/MM/YYYY'));
INSERT INTO KLANTORDER (KLANT_KLANTID, WINKEL_WINKEL_ID, PRIJS, ORDER_DATUM)
VALUES ((select KLANTID from KLANT where NAAM = 'Bob Debower'),
        (select WINKEL_ID from WINKEL where WINKEL_ADRES = 'Keyserlei 7 2000'), 559,
        to_date('4-12-2019', 'DD/MM/YYYY'));

--orderlijn
INSERT INTO orderlijn (CONSOLE_CONSOLENAAM, AANTAL, PRIJS, KLANTORDER_WINKEL_ID, KLANTORDER_KLANTID, KLANTORDER_ORDERID)
VALUES ('PlayStation 4', 2, 840,
        (SELECT WINKEL_ID FROM WINKEL WHERE WINKEL_ADRES = 'Frankrijklei 28 2000'),
        (SELECT KLANTID FROM KLANT WHERE NAAM = 'Sophie Vandenberghe'),
        (SELECT orderid
         FROM KLANTORDER
         WHERE KLANT_KLANTID = (SELECT KLANTID FROM KLANT WHERE NAAM = 'Sophie Vandenberghe')
           and WINKEL_WINKEL_ID = (SELECT WINKEL_ID FROM WINKEL WHERE WINKEL_ADRES = 'Frankrijklei 28 2000')
           and ORDER_DATUM = to_date('11-12-2020', 'DD/MM/YYYY')));


INSERT INTO orderlijn (CONSOLE_CONSOLENAAM, AANTAL, PRIJS, KLANTORDER_WINKEL_ID, KLANTORDER_KLANTID, KLANTORDER_ORDERID)
VALUES ('Ninetendo Switch', 1, 210,
        (SELECT WINKEL_ID FROM WINKEL WHERE WINKEL_ADRES = 'Huidevetterstraat 2 2000'),
        (SELECT KLANTID FROM KLANT where NAAM = 'Karen Willems'),
        (SELECT orderid FROM KLANTORDER WHERE KLANT_KLANTID = (SELECT KLANTID FROM KLANT where NAAM = 'Karen Willems')
                                          and WINKEL_WINKEL_ID = (SELECT WINKEL_ID FROM WINKEL WHERE WINKEL_ADRES = 'Huidevetterstraat 2 2000')
                                          and ORDER_DATUM = to_date('2-4-2021', 'DD/MM/YYYY')));

INSERT INTO orderlijn (CONSOLE_CONSOLENAAM, AANTAL, PRIJS, KLANTORDER_WINKEL_ID, KLANTORDER_KLANTID, KLANTORDER_ORDERID)
VALUES ('Nintendo Switch', 2, 420,
        (SELECT WINKEL_ID FROM WINKEL WHERE WINKEL_ADRES = 'Frankrijklei 28 2000'),
        (SELECT KLANTID FROM KLANT WHERE NAAM = 'Sophie Vandenberghe'),
        (SELECT orderid FROM KLANTORDER WHERE KLANT_KLANTID = (SELECT KLANTID FROM KLANT WHERE NAAM = 'Sophie Vandenberghe')
                                          and WINKEL_WINKEL_ID = (SELECT WINKEL_ID FROM WINKEL WHERE WINKEL_ADRES = 'Frankrijklei 28 2000')
                                          and ORDER_DATUM = to_date('20-6-2020', 'DD/MM/YYYY')));

INSERT INTO orderlijn (CONSOLE_CONSOLENAAM, AANTAL, PRIJS, KLANTORDER_WINKEL_ID, KLANTORDER_KLANTID, KLANTORDER_ORDERID)
VALUES ('Xbox series x', 1, 559,
        (select WINKEL_ID from WINKEL where WINKEL_ADRES = 'Keyserlei 7 2000'),
        (select KLANTID from KLANT where NAAM = 'Bob Debower'),
        (SELECT orderid FROM KLANTORDER WHERE KLANT_KLANTID = (select KLANTID from KLANT where NAAM = 'Bob Debower')
                                          and WINKEL_WINKEL_ID = (select WINKEL_ID from WINKEL where WINKEL_ADRES = 'Keyserlei 7 2000')
                                          and ORDER_DATUM = to_date('4-12-2019', 'DD/MM/YYYY')));

INSERT INTO orderlijn (CONSOLE_CONSOLENAAM, AANTAL, PRIJS, KLANTORDER_WINKEL_ID, KLANTORDER_KLANTID, KLANTORDER_ORDERID)
VALUES ('Steam Deck', 1, 779,
        (select WINKEL_ID from WINKEL where WINKEL_ADRES = 'Keyserlei 7 2000'),
        (select KLANTID from KLANT where NAAM = 'Bob Debower'),
        (SELECT orderid FROM KLANTORDER WHERE KLANT_KLANTID = (select KLANTID from KLANT where NAAM = 'Bob Debower')
                                          and WINKEL_WINKEL_ID = (select WINKEL_ID from WINKEL where WINKEL_ADRES = 'Keyserlei 7 2000')
                                          and ORDER_DATUM = to_date('17-4-2023', 'DD/MM/YYYY')));
