--table count

SELECT 'BEDRIJF' AS TABLE_NAME, (SELECT count(*) FROM BEDRIJF ) AS TABLE_COUNT
FROM dual
UNION
SELECT 'CONSOLE', (SELECT count(*) FROM CONSOLE)
FROM dual
UNION
SELECT 'KLANT', (SELECT count(*) FROM KLANT)
FROM dual
UNION
SELECT 'KLANTORDER', (SELECT count(*) FROM KLANTORDER)
FROM dual
UNION
SELECT 'LEVERING', (SELECT count(*) FROM LEVERING)
FROM dual
UNION
SELECT 'ORDERLIJN', (SELECT count(*) FROM ORDERLIJN)
FROM dual
UNION
SELECT 'WERKNEMER', (SELECT count(*) FROM WERKNEMER)
FROM dual
UNION
SELECT 'WINKEL', (SELECT count(*) FROM WINKEL)
FROM dual;

--select veel op veel
SELECT C.CONSOLENAAM, C.RELEASE, W.WINKEL_NAAM, W.Winkel_ADRES, W.STOCK
FROM CONSOLE C
JOIN LEVERING L on C.CONSOLEID = L.CONSOLE_CONSOLEID
JOIN WINKEL W on L.WINKEL_WINKEL_ID = W.WINKEL_ID;

--2 nievaus diep
SELECT W.WINKEL_NAAM, K.NAAM , KO.ORDERID, KO.PRIJS, O.AANTAL, O.CONSOLE_CONSOLENAAM
FROM WINKEL W
JOIN KLANTORDER KO on W.WINKEL_ID = KO.WINKEL_WINKEL_ID
JOIN KLANT K on K.KLANTID = KO.KLANT_KLANTID
JOIN ORDERLIJN O on KO.ORDERID = O.KLANTORDER_ORDERID and KO.WINKEL_WINKEL_ID = O.KLANTORDER_WINKEL_ID and KO.KLANT_KLANTID = O.KLANTORDER_KLANTID
ORDER BY K.NAAM;

--werknemers
SELECT W.WINKEL_NAAM, W.WINKEL_ADRES, WN.WERKNEMER_VOORNAAM, WN.WERKNEMER_ACHTERNAAM, WN.IS_MANAGER
FROM WINKEL W
JOIN WERKNEMER WN on W.WINKEL_ID = WN.WINKEL_WINKEL_ID
ORDER BY W.WINKEL_NAAM;

--bedrijven
SELECT C.CONSOLENAAM, C.PRIJS, B.NAAM, B.BEDRIJF_ADRES, B.BEDRIJF_LAND
FROM CONSOLE C
JOIN BEDRIJF B on C.CONSOLEID = B.CONSOLE_CONSOLEID
ORDER BY C.CONSOLENAAM;
